-include Makefile.header

all:
	cd DOM; ${MAKE}
	cd SAX2DOM; ${MAKE}
	cd XPath; ${MAKE}
	cd XPath_wide; ${MAKE}
	cd XPath_silly; ${MAKE}

clean:
	cd DOM; ${MAKE} clean
	cd SAX2DOM; ${MAKE} clean
	cd XPath; ${MAKE} clean
	cd XPath_wide; ${MAKE} clean
	cd XPath_silly; ${MAKE} clean

