
/*
This c++ source file was generated by for Arabica
and is a derived work from the source document.
The source document contained the following notice:


Copyright (c) 2001 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

*/

#ifndef test_cdatasectionnormalize
#define test_cdatasectionnormalize

#include "dom_conf_test.hpp"

/**
 * Adjacent CDATASection nodes cannot be merged together by
 * use of the "normalize()" method from the Element interface.
 * Retrieve second child of the second employee and invoke
 * the "normalize()" method.  The Element under contains
 * two CDATASection nodes that should not be merged together
 * by the "normalize()" method.
* @author NIST
* @author Mary Brady
* @see <a href="http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-162CF083">http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-162CF083</a>
*/

template<class string_type, class string_adaptor>
class cdatasectionnormalize : public DOMTestCase<string_type, string_adaptor> 
{
   public: 
     cdatasectionnormalize(std::string name) : DOMTestCase(name)
     {

       //   check if loaded documents are supported for content type
       const std::string contentType = getContentType();
    preload(contentType, "staff", true);
    }

  typedef typename DOMTestCase<string_type, string_adaptor> baseT;
  using baseT::DOMImplementation;
  using baseT::Document; 
  using baseT::DocumentType;
  using baseT::DocumentFragment; 
  using baseT::Node;
  using baseT::Element;
  using baseT::Attr;
  using baseT::NodeList;
  using baseT::NamedNodeMap;
  using baseT::Entity;
  using baseT::EntityReference;
  using baseT::CharacterData;
  using baseT::CDATASection;
  using baseT::Text;
  using baseT::Comment;
  using baseT::ProcessingInstruction;
  using baseT::Notation;

  typedef typename Arabica::DOM::DOMException DOMException;
  typedef string_type String;
  typedef string_adaptor SA;
  typedef bool boolean;

   /*
    * Runs the test case.
    */
   void runTest()
   {
      Document doc;
      NodeList nameList;
      Element lChild;
      NodeList childNodes;
      CDATASection cdataN;
      String data;
      doc = (Document) load("staff", true);
      nameList = doc.getElementsByTagName(SA::construct_from_utf8("name"));
      lChild = (Element) nameList.item(1);
      lChild.normalize();
      childNodes = lChild.getChildNodes();
      cdataN = (CDATASection) childNodes.item(1);
      assertNotNull(cdataN);
      data = cdataN.getData();
      assertEquals("This is a CDATASection with EntityReference number 2 &ent2;", data);
  cdataN = (CDATASection) childNodes.item(3);
      assertNotNull(cdataN);
      data = cdataN.getData();
      assertEquals("This is an adjacent CDATASection with a reference to a tab &tab;", data);
  
   }
  
   /*
    *  Gets URI that identifies the test.
    */
   std::string getTargetURI() const
   {
      return "http://www.w3.org/2001/DOM-Test-Suite/level1/core/cdatasectionnormalize";
   }
};

#endif
