
/*
This c++ source file was generated by for Arabica
and is a derived work from the source document.
The source document contained the following notice:


Copyright (c) 2001-2004 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

*/

#ifndef test_documenttypegetentitiestype
#define test_documenttypegetentitiestype

#include "dom_conf_test.hpp"

/**
 *     Every node in the map returned by the "getEntities()"
 *    method implements the Entity interface.
 *    
 *    Retrieve the Document Type for this document and create 
 *    a NamedNodeMap of all its entities.  Traverse the 
 *    entire list and examine the NodeType of each node
 *    in the list.
* @author NIST
* @author Mary Brady
* @see <a href="http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-1788794630">http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-1788794630</a>
*/

template<class string_type, class string_adaptor>
class documenttypegetentitiestype : public DOMTestCase<string_type, string_adaptor> 
{
   public: 
     documenttypegetentitiestype(std::string name) : DOMTestCase(name)
     {

       //   check if loaded documents are supported for content type
       const std::string contentType = getContentType();
    preload(contentType, "staff", false);
    }

  typedef typename DOMTestCase<string_type, string_adaptor> baseT;
  using baseT::DOMImplementation;
  using baseT::Document; 
  using baseT::DocumentType;
  using baseT::DocumentFragment; 
  using baseT::Node;
  using baseT::Element;
  using baseT::Attr;
  using baseT::NodeList;
  using baseT::NamedNodeMap;
  using baseT::Entity;
  using baseT::EntityReference;
  using baseT::CharacterData;
  using baseT::CDATASection;
  using baseT::Text;
  using baseT::Comment;
  using baseT::ProcessingInstruction;
  using baseT::Notation;

  typedef typename Arabica::DOM::DOMException DOMException;
  typedef string_type String;
  typedef string_adaptor SA;
  typedef bool boolean;

   /*
    * Runs the test case.
    */
   void runTest()
   {
      Document doc;
      DocumentType docType;
      NamedNodeMap entityList;
      Node entity;
      int entityType;
      doc = (Document) load("staff", false);
      docType = doc.getDoctype();
      assertNotNull(docType);
      entityList = docType.getEntities();
      assertNotNull(entityList);
      for (int indexN65609 = 0; indexN65609 != entityList.getLength(); indexN65609++) {
          entity = (Node) entityList.item(indexN65609);
    entityType = (int) entity.getNodeType();
      assertEquals(6, entityType);
    }
      
   }
  
   /*
    *  Gets URI that identifies the test.
    */
   std::string getTargetURI() const
   {
      return "http://www.w3.org/2001/DOM-Test-Suite/level1/core/documenttypegetentitiestype";
   }
};

#endif
