
/*
This c++ source file was generated by for Arabica
and is a derived work from the source document.
The source document contained the following notice:


Copyright (c) 2001-2004 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

*/

#ifndef test_elementgetelementsbytagnamespecialvalue
#define test_elementgetelementsbytagnamespecialvalue

#include "dom_conf_test.hpp"

/**
 * The "getElementsByTagName(name)" method may use the
 * special value "*" to match all tags in the element
 * tree.
 * Create a NodeList of all the descendant elements
 * of the last employee by using the special value "*".
 * The method should return all the descendant children(6)
 * in the order the children were encountered.
* @author NIST
* @author Mary Brady
* @see <a href="http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-1938918D">http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-1938918D</a>
*/

template<class string_type, class string_adaptor>
class elementgetelementsbytagnamespecialvalue : public DOMTestCase<string_type, string_adaptor> 
{
   public: 
     elementgetelementsbytagnamespecialvalue(std::string name) : DOMTestCase(name)
     {

       //   check if loaded documents are supported for content type
       const std::string contentType = getContentType();
    preload(contentType, "staff", false);
    }

  typedef typename DOMTestCase<string_type, string_adaptor> baseT;
  using baseT::DOMImplementation;
  using baseT::Document; 
  using baseT::DocumentType;
  using baseT::DocumentFragment; 
  using baseT::Node;
  using baseT::Element;
  using baseT::Attr;
  using baseT::NodeList;
  using baseT::NamedNodeMap;
  using baseT::Entity;
  using baseT::EntityReference;
  using baseT::CharacterData;
  using baseT::CDATASection;
  using baseT::Text;
  using baseT::Comment;
  using baseT::ProcessingInstruction;
  using baseT::Notation;

  typedef typename Arabica::DOM::DOMException DOMException;
  typedef string_type String;
  typedef string_adaptor SA;
  typedef bool boolean;

   /*
    * Runs the test case.
    */
   void runTest()
   {
      Document doc;
      NodeList elementList;
      Element lastEmployee;
      NodeList lastempList;
      Node child;
      String childName;
      std::vector<string_type> result;
      
      std::vector<string_type> expectedResult;
      expectedResult.push_back(SA::construct_from_utf8("employeeId"));
      expectedResult.push_back(SA::construct_from_utf8("name"));
      expectedResult.push_back(SA::construct_from_utf8("position"));
      expectedResult.push_back(SA::construct_from_utf8("salary"));
      expectedResult.push_back(SA::construct_from_utf8("gender"));
      expectedResult.push_back(SA::construct_from_utf8("address"));
      
      doc = (Document) load("staff", false);
      elementList = doc.getElementsByTagName(SA::construct_from_utf8("employee"));
      lastEmployee = (Element) elementList.item(4);
      lastempList = lastEmployee.getElementsByTagName(SA::construct_from_utf8("*"));
      for (int indexN65642 = 0; indexN65642 != lastempList.getLength(); indexN65642++) {
          child = (Node) lastempList.item(indexN65642);
    childName = child.getNodeName();
      result.push_back(childName);
        }
      assertEquals(expectedResult, result);
  
   }
  
   /*
    *  Gets URI that identifies the test.
    */
   std::string getTargetURI() const
   {
      return "http://www.w3.org/2001/DOM-Test-Suite/level1/core/elementgetelementsbytagnamespecialvalue";
   }
};

#endif
