
/*
This c++ source file was generated by for Arabica
and is a derived work from the source document.
The source document contained the following notice:


Copyright (c) 2001 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

*/

#ifndef test_elementnormalize
#define test_elementnormalize

#include "dom_conf_test.hpp"

/**
 *     The "normalize()" method puts all the nodes in the full
 *    depth of the sub-tree underneath this element into a 
 *    "normal" form. 
 *    
 *    Retrieve the third employee and access its second child.
 *    This child contains a block of text that is spread 
 *    across multiple lines.  The content of the "name" child
 *    should be parsed and treated as a single Text node.
* @author NIST
* @author Mary Brady
* @see <a href="http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-162CF083">http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-162CF083</a>
*/

template<class string_type, class string_adaptor>
class elementnormalize : public DOMTestCase<string_type, string_adaptor> 
{
   public: 
     elementnormalize(std::string name) : DOMTestCase(name)
     {

       //   check if loaded documents are supported for content type
       const std::string contentType = getContentType();
    preload(contentType, "staff", true);
    }

  typedef typename DOMTestCase<string_type, string_adaptor> baseT;
  using baseT::DOMImplementation;
  using baseT::Document; 
  using baseT::DocumentType;
  using baseT::DocumentFragment; 
  using baseT::Node;
  using baseT::Element;
  using baseT::Attr;
  using baseT::NodeList;
  using baseT::NamedNodeMap;
  using baseT::Entity;
  using baseT::EntityReference;
  using baseT::CharacterData;
  using baseT::CDATASection;
  using baseT::Text;
  using baseT::Comment;
  using baseT::ProcessingInstruction;
  using baseT::Notation;

  typedef typename Arabica::DOM::DOMException DOMException;
  typedef string_type String;
  typedef string_adaptor SA;
  typedef bool boolean;

   /*
    * Runs the test case.
    */
   void runTest()
   {
      Document doc;
      Element root;
      NodeList elementList;
      Element testName;
      Node firstChild;
      String childValue;
      doc = (Document) load("staff", true);
      root = doc.getDocumentElement();
      root.normalize();
      elementList = root.getElementsByTagName(SA::construct_from_utf8("name"));
      testName = (Element) elementList.item(2);
      firstChild = testName.getFirstChild();
      childValue = firstChild.getNodeValue();
      assertEquals("Roger\n Jones", childValue);
  
   }
  
   /*
    *  Gets URI that identifies the test.
    */
   std::string getTargetURI() const
   {
      return "http://www.w3.org/2001/DOM-Test-Suite/level1/core/elementnormalize";
   }
};

#endif
