
/*
This c++ source file was generated by for Arabica
and is a derived work from the source document.
The source document contained the following notice:


Copyright (c) 2001-2003 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

*/

#ifndef test_hc_documentcreateelementcasesensitive
#define test_hc_documentcreateelementcasesensitive

#include "dom_conf_test.hpp"

/**
 *     The tagName parameter in the "createElement(tagName)"
 *    method is case-sensitive for XML documents.
 *    Retrieve the entire DOM document and invoke its 
 *    "createElement(tagName)" method twice.  Once for tagName
 *    equal to "acronym" and once for tagName equal to "ACRONYM"
 *    Each call should create a distinct Element node.  The
 *    newly created Elements are then assigned attributes 
 *    that are retrieved.
 *    Modified on 27 June 2003 to avoid setting an invalid style
 *    values and checked the node names to see if they matched expectations.
* @author Curt Arnold
* @see <a href="http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-2141741547">http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-2141741547</a>
* @see <a href="http://www.w3.org/Bugs/Public/show_bug.cgi?id=243">http://www.w3.org/Bugs/Public/show_bug.cgi?id=243</a>
*/

template<class string_type, class string_adaptor>
class hc_documentcreateelementcasesensitive : public DOMTestCase<string_type, string_adaptor> 
{
   public: 
     hc_documentcreateelementcasesensitive(std::string name) : DOMTestCase(name)
     {

       //   check if loaded documents are supported for content type
       const std::string contentType = getContentType();
    preload(contentType, "hc_staff", true);
    }

  typedef typename DOMTestCase<string_type, string_adaptor> baseT;
  using baseT::DOMImplementation;
  using baseT::Document; 
  using baseT::DocumentType;
  using baseT::DocumentFragment; 
  using baseT::Node;
  using baseT::Element;
  using baseT::Attr;
  using baseT::NodeList;
  using baseT::NamedNodeMap;
  using baseT::Entity;
  using baseT::EntityReference;
  using baseT::CharacterData;
  using baseT::CDATASection;
  using baseT::Text;
  using baseT::Comment;
  using baseT::ProcessingInstruction;
  using baseT::Notation;

  typedef typename Arabica::DOM::DOMException DOMException;
  typedef string_type String;
  typedef string_adaptor SA;
  typedef bool boolean;

   /*
    * Runs the test case.
    */
   void runTest()
   {
      Document doc;
      Element newElement1;
      Element newElement2;
      String attribute1;
      String attribute2;
      String nodeName1;
      String nodeName2;
      doc = (Document) load("hc_staff", true);
      newElement1 = doc.createElement(SA::construct_from_utf8("ACRONYM"));
      newElement2 = doc.createElement(SA::construct_from_utf8("acronym"));
      newElement1.setAttribute(SA::construct_from_utf8("lang"), SA::construct_from_utf8("EN"));
      newElement2.setAttribute(SA::construct_from_utf8("title"), SA::construct_from_utf8("Dallas"));
      attribute1 = newElement1.getAttribute(SA::construct_from_utf8("lang"));
      attribute2 = newElement2.getAttribute(SA::construct_from_utf8("title"));
      assertEquals("EN", attribute1);
  assertEquals("Dallas", attribute2);
  nodeName1 = newElement1.getNodeName();
      nodeName2 = newElement2.getNodeName();
      assertEquals("ACRONYM", nodeName1);
  assertEquals("acronym", nodeName2);
  
   }
  
   /*
    *  Gets URI that identifies the test.
    */
   std::string getTargetURI() const
   {
      return "http://www.w3.org/2001/DOM-Test-Suite/level1/core/hc_documentcreateelementcasesensitive";
   }
};

#endif
