
/*
This c++ source file was generated by for Arabica
and is a derived work from the source document.
The source document contained the following notice:


Copyright (c) 2001-2004 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

*/

#ifndef test_hc_elementnormalize2
#define test_hc_elementnormalize2

#include "dom_conf_test.hpp"

/**
 * Add an empty text node to an existing attribute node, normalize the containing element
 * and check that the attribute node has eliminated the empty text.
* @author Curt Arnold
* @see <a href="http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-162CF083">http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-162CF083</a>
* @see <a href="http://www.w3.org/Bugs/Public/show_bug.cgi?id=482">http://www.w3.org/Bugs/Public/show_bug.cgi?id=482</a>
*/

template<class string_type, class string_adaptor>
class hc_elementnormalize2 : public DOMTestCase<string_type, string_adaptor> 
{
   public: 
     hc_elementnormalize2(std::string name) : DOMTestCase(name)
     {

       //   check if loaded documents are supported for content type
       const std::string contentType = getContentType();
    preload(contentType, "hc_staff", true);
    }

  typedef typename DOMTestCase<string_type, string_adaptor> baseT;
  using baseT::DOMImplementation;
  using baseT::Document; 
  using baseT::DocumentType;
  using baseT::DocumentFragment; 
  using baseT::Node;
  using baseT::Element;
  using baseT::Attr;
  using baseT::NodeList;
  using baseT::NamedNodeMap;
  using baseT::Entity;
  using baseT::EntityReference;
  using baseT::CharacterData;
  using baseT::CDATASection;
  using baseT::Text;
  using baseT::Comment;
  using baseT::ProcessingInstruction;
  using baseT::Notation;

  typedef typename Arabica::DOM::DOMException DOMException;
  typedef string_type String;
  typedef string_adaptor SA;
  typedef bool boolean;

   /*
    * Runs the test case.
    */
   void runTest()
   {
      Document doc;
      Element root;
      NodeList elementList;
      Element element;
      Node firstChild;
      Node secondChild;
      String childValue;
      Text emptyText;
      Attr attrNode;
      Node retval;
      doc = (Document) load("hc_staff", true);
      root = doc.getDocumentElement();
      emptyText = doc.createTextNode(SA::construct_from_utf8(""));
      elementList = root.getElementsByTagName(SA::construct_from_utf8("acronym"));
      element = (Element) elementList.item(0);
      attrNode = element.getAttributeNode(SA::construct_from_utf8("title"));
      retval = attrNode.appendChild(emptyText);
      element.normalize();
      attrNode = element.getAttributeNode(SA::construct_from_utf8("title"));
      firstChild = attrNode.getFirstChild();
      childValue = firstChild.getNodeValue();
      assertEquals("Yes", childValue);
  secondChild = firstChild.getNextSibling();
      assertNull(secondChild);
      
   }
  
   /*
    *  Gets URI that identifies the test.
    */
   std::string getTargetURI() const
   {
      return "http://www.w3.org/2001/DOM-Test-Suite/level1/core/hc_elementnormalize2";
   }
};

#endif
