
/*
This c++ source file was generated by for Arabica
and is a derived work from the source document.
The source document contained the following notice:


Copyright (c) 2001-2003 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

*/

#ifndef test_hc_nodecommentnodetype
#define test_hc_nodecommentnodetype

#include "dom_conf_test.hpp"

/**
 *     The "getNodeType()" method for a Comment Node
 *     returns the constant value 8.
 *     
 *     Retrieve the nodes from the document and check for
 *     a comment node and invoke the "getNodeType()" method.   This should   
 *     return 8. 
* @author Curt Arnold
* @see <a href="http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-111237558">http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-111237558</a>
* @see <a href="http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-1728279322">http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-1728279322</a>
* @see <a href="http://www.w3.org/Bugs/Public/show_bug.cgi?id=248">http://www.w3.org/Bugs/Public/show_bug.cgi?id=248</a>
*/

template<class string_type, class string_adaptor>
class hc_nodecommentnodetype : public DOMTestCase<string_type, string_adaptor> 
{
   public: 
     hc_nodecommentnodetype(std::string name) : DOMTestCase(name)
     {

       //   check if loaded documents are supported for content type
       const std::string contentType = getContentType();
    preload(contentType, "hc_staff", false);
    }

  typedef typename DOMTestCase<string_type, string_adaptor> baseT;
  using baseT::DOMImplementation;
  using baseT::Document; 
  using baseT::DocumentType;
  using baseT::DocumentFragment; 
  using baseT::Node;
  using baseT::Element;
  using baseT::Attr;
  using baseT::NodeList;
  using baseT::NamedNodeMap;
  using baseT::Entity;
  using baseT::EntityReference;
  using baseT::CharacterData;
  using baseT::CDATASection;
  using baseT::Text;
  using baseT::Comment;
  using baseT::ProcessingInstruction;
  using baseT::Notation;

  typedef typename Arabica::DOM::DOMException DOMException;
  typedef string_type String;
  typedef string_adaptor SA;
  typedef bool boolean;

   /*
    * Runs the test case.
    */
   void runTest()
   {
      Document doc;
      NodeList testList;
      Node commentNode;
      String commentNodeName;
      int nodeType;
      doc = (Document) load("hc_staff", false);
      testList = doc.getChildNodes();
      for (int indexN65600 = 0; indexN65600 != testList.getLength(); indexN65600++) {
          commentNode = (Node) testList.item(indexN65600);
    commentNodeName = commentNode.getNodeName();
      
      if (equals("#comment", commentNodeName)) {
          nodeType = (int) commentNode.getNodeType();
      assertEquals(8, nodeType);
  }
      }
      commentNode = doc.createComment(SA::construct_from_utf8("This is a comment"));
      nodeType = (int) commentNode.getNodeType();
      assertEquals(8, nodeType);
  
   }
  
   /*
    *  Gets URI that identifies the test.
    */
   std::string getTargetURI() const
   {
      return "http://www.w3.org/2001/DOM-Test-Suite/level1/core/hc_nodecommentnodetype";
   }
};

#endif
