
/*
This c++ source file was generated by for Arabica
and is a derived work from the source document.
The source document contained the following notice:


Copyright (c) 2001-2003 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

*/

#ifndef test_hc_nodecommentnodeattributes
#define test_hc_nodecommentnodeattributes

#include "dom_conf_test.hpp"

/**
 *     The "getAttributes()" method invoked on a Comment 
 *     Node returns null.
 *     Find any comment that is an immediate child of the root
 *     and assert that Node.attributes is null.  Then create
 *     a new comment node (in case they had been omitted) and
 *     make the assertion.    
* @author Curt Arnold
* @see <a href="http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-84CF096">http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-84CF096</a>
* @see <a href="http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-1728279322">http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-1728279322</a>
* @see <a href="http://www.w3.org/Bugs/Public/show_bug.cgi?id=248">http://www.w3.org/Bugs/Public/show_bug.cgi?id=248</a>
* @see <a href="http://www.w3.org/Bugs/Public/show_bug.cgi?id=263">http://www.w3.org/Bugs/Public/show_bug.cgi?id=263</a>
*/

template<class string_type, class string_adaptor>
class hc_nodecommentnodeattributes : public DOMTestCase<string_type, string_adaptor> 
{
   public: 
     hc_nodecommentnodeattributes(std::string name) : DOMTestCase(name)
     {

       //   check if loaded documents are supported for content type
       const std::string contentType = getContentType();
    preload(contentType, "hc_staff", false);
    }

  typedef typename DOMTestCase<string_type, string_adaptor> baseT;
  using baseT::DOMImplementation;
  using baseT::Document; 
  using baseT::DocumentType;
  using baseT::DocumentFragment; 
  using baseT::Node;
  using baseT::Element;
  using baseT::Attr;
  using baseT::NodeList;
  using baseT::NamedNodeMap;
  using baseT::Entity;
  using baseT::EntityReference;
  using baseT::CharacterData;
  using baseT::CDATASection;
  using baseT::Text;
  using baseT::Comment;
  using baseT::ProcessingInstruction;
  using baseT::Notation;

  typedef typename Arabica::DOM::DOMException DOMException;
  typedef string_type String;
  typedef string_adaptor SA;
  typedef bool boolean;

   /*
    * Runs the test case.
    */
   void runTest()
   {
      Document doc;
      Node commentNode;
      NodeList nodeList;
      NamedNodeMap attrList;
      int nodeType;
      doc = (Document) load("hc_staff", false);
      nodeList = doc.getChildNodes();
      for (int indexN65603 = 0; indexN65603 != nodeList.getLength(); indexN65603++) {
          commentNode = (Node) nodeList.item(indexN65603);
    nodeType = (int) commentNode.getNodeType();
      
      if (equals(8, nodeType)) {
          attrList = commentNode.getAttributes();
      assertNull(attrList);
      }
      }
      commentNode = doc.createComment(SA::construct_from_utf8("This is a comment"));
      attrList = commentNode.getAttributes();
      assertNull(attrList);
      
   }
  
   /*
    *  Gets URI that identifies the test.
    */
   std::string getTargetURI() const
   {
      return "http://www.w3.org/2001/DOM-Test-Suite/level1/core/hc_nodecommentnodeattributes";
   }
};

#endif
