
/*
This c++ source file was generated by for Arabica
and is a derived work from the source document.
The source document contained the following notice:


Copyright (c) 2001-2004 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

*/

#ifndef test_nodereplacechildnewchildexists
#define test_nodereplacechildnewchildexists

#include "dom_conf_test.hpp"

/**
 *     Retrieve the second employee and replace its TWELFTH 
 *     child(address) with its SECOND child(employeeId).   After the
 *     replacement the second child should now be the one that used   
 *     to be at the third position and the TWELFTH child should be the
 *     one that used to be at the SECOND position.
* @author NIST
* @author Mary Brady
* @see <a href="http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-785887307">http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-785887307</a>
*/

template<class string_type, class string_adaptor>
class nodereplacechildnewchildexists : public DOMTestCase<string_type, string_adaptor> 
{
   public: 
     nodereplacechildnewchildexists(std::string name) : DOMTestCase(name)
     {

       //   check if loaded documents are supported for content type
       const std::string contentType = getContentType();
    preload(contentType, "staff", true);
    }

  typedef typename DOMTestCase<string_type, string_adaptor> baseT;
  using baseT::DOMImplementation;
  using baseT::Document; 
  using baseT::DocumentType;
  using baseT::DocumentFragment; 
  using baseT::Node;
  using baseT::Element;
  using baseT::Attr;
  using baseT::NodeList;
  using baseT::NamedNodeMap;
  using baseT::Entity;
  using baseT::EntityReference;
  using baseT::CharacterData;
  using baseT::CDATASection;
  using baseT::Text;
  using baseT::Comment;
  using baseT::ProcessingInstruction;
  using baseT::Notation;

  typedef typename Arabica::DOM::DOMException DOMException;
  typedef string_type String;
  typedef string_adaptor SA;
  typedef bool boolean;

   /*
    * Runs the test case.
    */
   void runTest()
   {
      Document doc;
      NodeList elementList;
      Node employeeNode;
      NodeList childList;
      Node oldChild;
      Node newChild;
      String childName;
      Node childNode;
      int length;
      std::vector<string_type> actual;
      
      std::vector<string_type> expected;
      
      std::vector<string_type> expectedWithoutWhitespace;
      expectedWithoutWhitespace.push_back(SA::construct_from_utf8("name"));
      expectedWithoutWhitespace.push_back(SA::construct_from_utf8("position"));
      expectedWithoutWhitespace.push_back(SA::construct_from_utf8("salary"));
      expectedWithoutWhitespace.push_back(SA::construct_from_utf8("gender"));
      expectedWithoutWhitespace.push_back(SA::construct_from_utf8("employeeId"));
      
      std::vector<string_type> expectedWithWhitespace;
      expectedWithWhitespace.push_back(SA::construct_from_utf8("#text"));
      expectedWithWhitespace.push_back(SA::construct_from_utf8("#text"));
      expectedWithWhitespace.push_back(SA::construct_from_utf8("name"));
      expectedWithWhitespace.push_back(SA::construct_from_utf8("#text"));
      expectedWithWhitespace.push_back(SA::construct_from_utf8("position"));
      expectedWithWhitespace.push_back(SA::construct_from_utf8("#text"));
      expectedWithWhitespace.push_back(SA::construct_from_utf8("salary"));
      expectedWithWhitespace.push_back(SA::construct_from_utf8("#text"));
      expectedWithWhitespace.push_back(SA::construct_from_utf8("gender"));
      expectedWithWhitespace.push_back(SA::construct_from_utf8("#text"));
      expectedWithWhitespace.push_back(SA::construct_from_utf8("employeeId"));
      expectedWithWhitespace.push_back(SA::construct_from_utf8("#text"));
      
      Node replacedChild;
      doc = (Document) load("staff", true);
      elementList = doc.getElementsByTagName(SA::construct_from_utf8("employee"));
      employeeNode = elementList.item(1);
      childList = employeeNode.getChildNodes();
      length = (int) childList.getLength();
      
      if (equals(13, length)) {
          newChild = childList.item(1);
      oldChild = childList.item(11);
      expected =  expectedWithWhitespace;
      } else {
          newChild = childList.item(0);
      oldChild = childList.item(5);
      expected =  expectedWithoutWhitespace;
      }
        
    replacedChild = employeeNode.replaceChild(newChild, oldChild);
      assertSame(oldChild, replacedChild);
for (int indexN65758 = 0; indexN65758 != childList.getLength(); indexN65758++) {
          childNode = (Node) childList.item(indexN65758);
    childName = childNode.getNodeName();
      actual.push_back(childName);
        }
      assertEquals(expected, actual);
  
   }
  
   /*
    *  Gets URI that identifies the test.
    */
   std::string getTargetURI() const
   {
      return "http://www.w3.org/2001/DOM-Test-Suite/level1/core/nodereplacechildnewchildexists";
   }
};

#endif
