<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <xsl:attribute-set name="merge">
        <xsl:attribute name="attr1">attr1 pri -2</xsl:attribute>
        <xsl:attribute name="attr5">attr5 pri -2</xsl:attribute>
    </xsl:attribute-set>

    <xsl:attribute-set name="merge-import">
        <xsl:attribute name="merge-import-2"/>
    </xsl:attribute-set>

</xsl:stylesheet>