-include Makefile.header 

# High level rules
all : 
	cd SAX; ${MAKE}
	cd SAX2DOM; ${MAKE}
	cd XPath; ${MAKE}
	cd Utils; ${MAKE}

# Cleaning up

clean :
	cd SAX; ${MAKE} clean
	cd SAX2DOM; ${MAKE} clean
	cd XPath; ${MAKE} clean
	cd Utils; ${MAKE} clean

# End of File
