-include Makefile.header 

# High level rules
all : 
	${MAKE} --directory=SAX
	${MAKE} --directory=SAX2DOM
	${MAKE} --directory=XPath
	${MAKE} --directory=Utils

# Cleaning up

clean :
	${MAKE} --directory=SAX clean
	${MAKE} --directory=SAX2DOM clean
	${MAKE} --directory=XPath clean
	${MAKE} --directory=Utils clean

# End of File
